### ISSUE TITLE
Unable to locate package terraform op M1 macbook

### ISSUE THREAD

**Issue by 792x** [NavaraBV/kennisfestival-iac#6]
Hallo, bij het starten van de development container krijg ik de volgende error. Het lijkt er op dat terraform niet gevonden kan worden voor de darwin-arm64 architectuur.

```
[22 ms] Remote-Containers 0.231.3 in VS Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5).
[21 ms] Start: Resolving Remote
[34 ms] Setting up container for folder or workspace: /Users/casper/Code/Navara/kennisfestival-iac
[36 ms] Start: Check Docker is running
[36 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[155 ms] Server API version: 1.41
[156 ms] Start: Run: docker volume ls -q
[278 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/casper/Code/Navara/kennisfestival-iac --filter label=vsch.quality=stable
[411 ms] Start: Run: /Applications/Visual Studio Code.app/Contents/MacOS/Electron /Users/casper/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.3/dist/spec-node/devContainersSpecCLI.js up --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /Users/casper/Code/Navara/kennisfestival-iac --workspace-mount-consistency cached --id-label vsch.local.folder=/Users/casper/Code/Navara/kennisfestival-iac --id-label vsch.quality=stable --log-level debug --config /Users/casper/Code/Navara/kennisfestival-iac/.devcontainer/devcontainer.json --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[513 ms] remote-containers 0.231.3.
[513 ms] Start: Resolving Remote
[515 ms] Start: Run: git rev-parse --show-cdup
[524 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/casper/Code/Navara/kennisfestival-iac --filter label=vsch.quality=stable
[642 ms] Start: Run: docker build -f /Users/casper/Code/Navara/kennisfestival-iac/.devcontainer/Dockerfile -t vsc-kennisfestival-iac-e53690ef3aa9415bd23349b9ae9c8801 --build-arg VARIANT=16-bullseye /Users/casper/Code/Navara/kennisfestival-iac/.devcontainer
[+] Building 8.4s (5/5) FINISHED                                                
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 985B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/j  0.3s
 => CACHED [1/2] FROM mcr.microsoft.com/vscode/devcontainers/javascript-n  0.0s
 => ERROR [2/2] RUN apt-get update && export DEBIAN_FRONTEND=noninteracti  8.0s
------                                                                          
 > [2/2] RUN apt-get update && export DEBIAN_FRONTEND=noninteractive     && apt-get -y install --no-install-recommends software-properties-common     && curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -     && apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"     && apt-get update && export DEBIAN_FRONTEND=noninteractive     && apt-get -y install --no-install-recommends terraform     && npm install -g azure-functions-core-tools:
#5 0.256 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]         
#5 0.268 Get:2 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
#5 0.323 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
#5 0.395 Get:4 http://security.debian.org/debian-security bullseye-security/main arm64 Packages [123 kB]
#5 0.433 Get:5 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
#5 0.476 Get:6 http://deb.debian.org/debian bullseye/non-free arm64 Packages [69.6 kB]
#5 0.511 Get:7 http://deb.debian.org/debian bullseye/contrib arm64 Packages [40.8 kB]
#5 0.516 Get:8 http://deb.debian.org/debian bullseye/main arm64 Packages [8070 kB]
#5 0.613 Get:9 https://dl.yarnpkg.com/debian stable/main all Packages [10.6 kB]
#5 0.642 Get:10 https://dl.yarnpkg.com/debian stable/main arm64 Packages [10.6 kB]
#5 1.818 Get:11 http://deb.debian.org/debian bullseye-updates/main arm64 Packages [2596 B]
#5 2.500 Fetched 8544 kB in 2s (3702 kB/s)
#5 2.500 Reading package lists...
#5 2.829 Reading package lists...
#5 3.153 Building dependency tree...
#5 3.260 Reading state information...
#5 3.362 The following additional packages will be installed:
#5 3.362   gir1.2-glib-2.0 gir1.2-packagekitglib-1.0 iso-codes libdbus-1-3
#5 3.363   libgirepository-1.0-1 libpackagekit-glib2-18 python-apt-common python3-apt
#5 3.363   python3-dbus python3-gi python3-pycurl python3-software-properties
#5 3.363 Suggested packages:
#5 3.363   isoquery python3-apt-dbg python-apt-doc python-dbus-doc python3-dbus-dbg
#5 3.363   libcurl4-gnutls-dev python-pycurl-doc python3-pycurl-dbg
#5 3.363 Recommended packages:
#5 3.363   dbus packagekit unattended-upgrades
#5 3.438 The following NEW packages will be installed:
#5 3.438   gir1.2-glib-2.0 gir1.2-packagekitglib-1.0 iso-codes libdbus-1-3
#5 3.438   libgirepository-1.0-1 libpackagekit-glib2-18 python-apt-common python3-apt
#5 3.438   python3-dbus python3-gi python3-pycurl python3-software-properties
#5 3.438   software-properties-common
#5 3.497 0 upgraded, 13 newly installed, 0 to remove and 39 not upgraded.
#5 3.497 Need to get 4233 kB of archives.
#5 3.497 After this operation, 25.9 MB of additional disk space will be used.
#5 3.497 Get:1 http://deb.debian.org/debian bullseye/main arm64 libgirepository-1.0-1 arm64 1.66.1-1+b1 [88.6 kB]
#5 3.546 Get:2 http://deb.debian.org/debian bullseye/main arm64 gir1.2-glib-2.0 arm64 1.66.1-1+b1 [151 kB]
#5 3.564 Get:3 http://deb.debian.org/debian bullseye/main arm64 libpackagekit-glib2-18 arm64 1.2.2-2 [113 kB]
#5 3.571 Get:4 http://deb.debian.org/debian bullseye/main arm64 gir1.2-packagekitglib-1.0 arm64 1.2.2-2 [36.8 kB]
#5 3.572 Get:5 http://deb.debian.org/debian bullseye/main arm64 iso-codes all 4.6.0-1 [2824 kB]
#5 3.691 Get:6 http://deb.debian.org/debian bullseye/main arm64 libdbus-1-3 arm64 1.12.20-2 [208 kB]
#5 3.693 Get:7 http://deb.debian.org/debian bullseye/main arm64 python-apt-common all 2.2.1 [96.5 kB]
#5 3.707 Get:8 http://deb.debian.org/debian bullseye/main arm64 python3-apt arm64 2.2.1 [183 kB]
#5 3.719 Get:9 http://deb.debian.org/debian bullseye/main arm64 python3-dbus arm64 1.2.16-5 [105 kB]
#5 3.721 Get:10 http://deb.debian.org/debian bullseye/main arm64 python3-gi arm64 3.38.0-2 [226 kB]
#5 3.732 Get:11 http://deb.debian.org/debian bullseye/main arm64 python3-pycurl arm64 7.43.0.6-5 [67.9 kB]
#5 3.734 Get:12 http://deb.debian.org/debian bullseye/main arm64 python3-software-properties all 0.96.20.2-2.1 [49.7 kB]
#5 3.735 Get:13 http://deb.debian.org/debian bullseye/main arm64 software-properties-common all 0.96.20.2-2.1 [83.4 kB]
#5 4.182 Fetched 4233 kB in 0s (14.4 MB/s)
#5 4.199 Selecting previously unselected package libgirepository-1.0-1:arm64.
(Reading database ... 26879 files and directories currently installed.)
#5 4.212 Preparing to unpack .../00-libgirepository-1.0-1_1.66.1-1+b1_arm64.deb ...
#5 4.217 Unpacking libgirepository-1.0-1:arm64 (1.66.1-1+b1) ...
#5 4.239 Selecting previously unselected package gir1.2-glib-2.0:arm64.
#5 4.242 Preparing to unpack .../01-gir1.2-glib-2.0_1.66.1-1+b1_arm64.deb ...
#5 4.244 Unpacking gir1.2-glib-2.0:arm64 (1.66.1-1+b1) ...
#5 4.276 Selecting previously unselected package libpackagekit-glib2-18:arm64.
#5 4.278 Preparing to unpack .../02-libpackagekit-glib2-18_1.2.2-2_arm64.deb ...
#5 4.280 Unpacking libpackagekit-glib2-18:arm64 (1.2.2-2) ...
#5 4.305 Selecting previously unselected package gir1.2-packagekitglib-1.0.
#5 4.307 Preparing to unpack .../03-gir1.2-packagekitglib-1.0_1.2.2-2_arm64.deb ...
#5 4.310 Unpacking gir1.2-packagekitglib-1.0 (1.2.2-2) ...
#5 4.330 Selecting previously unselected package iso-codes.
#5 4.332 Preparing to unpack .../04-iso-codes_4.6.0-1_all.deb ...
#5 4.335 Unpacking iso-codes (4.6.0-1) ...
#5 4.609 Selecting previously unselected package libdbus-1-3:arm64.
#5 4.611 Preparing to unpack .../05-libdbus-1-3_1.12.20-2_arm64.deb ...
#5 4.614 Unpacking libdbus-1-3:arm64 (1.12.20-2) ...
#5 4.646 Selecting previously unselected package python-apt-common.
#5 4.648 Preparing to unpack .../06-python-apt-common_2.2.1_all.deb ...
#5 4.651 Unpacking python-apt-common (2.2.1) ...
#5 4.680 Selecting previously unselected package python3-apt.
#5 4.682 Preparing to unpack .../07-python3-apt_2.2.1_arm64.deb ...
#5 4.684 Unpacking python3-apt (2.2.1) ...
#5 4.716 Selecting previously unselected package python3-dbus.
#5 4.718 Preparing to unpack .../08-python3-dbus_1.2.16-5_arm64.deb ...
#5 4.720 Unpacking python3-dbus (1.2.16-5) ...
#5 4.747 Selecting previously unselected package python3-gi.
#5 4.749 Preparing to unpack .../09-python3-gi_3.38.0-2_arm64.deb ...
#5 4.751 Unpacking python3-gi (3.38.0-2) ...
#5 4.786 Selecting previously unselected package python3-pycurl.
#5 4.787 Preparing to unpack .../10-python3-pycurl_7.43.0.6-5_arm64.deb ...
#5 4.789 Unpacking python3-pycurl (7.43.0.6-5) ...
#5 4.814 Selecting previously unselected package python3-software-properties.
#5 4.816 Preparing to unpack .../11-python3-software-properties_0.96.20.2-2.1_all.deb ...
#5 4.819 Unpacking python3-software-properties (0.96.20.2-2.1) ...
#5 4.842 Selecting previously unselected package software-properties-common.
#5 4.843 Preparing to unpack .../12-software-properties-common_0.96.20.2-2.1_all.deb ...
#5 4.846 Unpacking software-properties-common (0.96.20.2-2.1) ...
#5 4.884 Setting up libpackagekit-glib2-18:arm64 (1.2.2-2) ...
#5 4.890 Setting up python3-pycurl (7.43.0.6-5) ...
#5 4.977 Setting up libdbus-1-3:arm64 (1.12.20-2) ...
#5 4.984 Setting up python-apt-common (2.2.1) ...
#5 4.991 Setting up libgirepository-1.0-1:arm64 (1.66.1-1+b1) ...
#5 4.995 Setting up iso-codes (4.6.0-1) ...
#5 5.000 Setting up python3-dbus (1.2.16-5) ...
#5 5.094 Setting up python3-apt (2.2.1) ...
#5 5.198 Setting up python3-software-properties (0.96.20.2-2.1) ...
#5 5.291 Setting up gir1.2-glib-2.0:arm64 (1.66.1-1+b1) ...
#5 5.298 Setting up gir1.2-packagekitglib-1.0 (1.2.2-2) ...
#5 5.303 Setting up python3-gi (3.38.0-2) ...
#5 5.417 Setting up software-properties-common (0.96.20.2-2.1) ...
#5 5.509 Processing triggers for man-db (2.9.4-2) ...
#5 5.621 Processing triggers for libc-bin (2.31-13+deb11u2) ...
#5 5.697 Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
#5 6.112 OK
#5 6.457 Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
#5 6.457 Hit:2 http://deb.debian.org/debian bullseye InRelease
#5 6.473 Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
#5 6.503 Hit:4 https://dl.yarnpkg.com/debian stable InRelease
#5 6.622 Get:5 https://apt.releases.hashicorp.com bullseye InRelease [10.3 kB]
#5 7.108 Get:6 https://apt.releases.hashicorp.com bullseye/main arm64 Packages [5294 B]
#5 7.133 Fetched 15.6 kB in 1s (20.9 kB/s)
#5 7.133 Reading package lists...
#5 7.474 Reading package lists...
#5 7.800 Building dependency tree...
#5 7.901 Reading state information...
#5 7.963 E: Unable to locate package terraform
------
executor failed running [/bin/sh -c apt-get update && export DEBIAN_FRONTEND=noninteractive     && apt-get -y install --no-install-recommends software-properties-common     && curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -     && apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"     && apt-get update && export DEBIAN_FRONTEND=noninteractive     && apt-get -y install --no-install-recommends terraform     && npm install -g azure-functions-core-tools]: exit code: 100
[9458 ms] Error: Command failed: docker build -f /Users/casper/Code/Navara/kennisfestival-iac/.devcontainer/Dockerfile -t vsc-kennisfestival-iac-e53690ef3aa9415bd23349b9ae9c8801 --build-arg VARIANT=16-bullseye /Users/casper/Code/Navara/kennisfestival-iac/.devcontainer
[9460 ms]     at Lu (/Users/casper/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.3/dist/spec-node/devContainersSpecCLI.js:218:3210)
[9460 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[9460 ms]     at async CR (/Users/casper/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.3/dist/spec-node/devContainersSpecCLI.js:218:1558)
[9461 ms]     at async qw (/Users/casper/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.3/dist/spec-node/devContainersSpecCLI.js:218:585)
[9462 ms]     at async RR (/Users/casper/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.3/dist/spec-node/devContainersSpecCLI.js:223:2024)
[9462 ms]     at async Jw (/Users/casper/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.3/dist/spec-node/devContainersSpecCLI.js:223:3221)
[9462 ms]     at async TR (/Users/casper/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.3/dist/spec-node/devContainersSpecCLI.js:223:13925)
[9462 ms]     at async FR (/Users/casper/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.3/dist/spec-node/devContainersSpecCLI.js:223:13650)
[9466 ms] Exit code 1
[9468 ms] Command failed: /Applications/Visual Studio Code.app/Contents/MacOS/Electron /Users/casper/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.3/dist/spec-node/devContainersSpecCLI.js up --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /Users/casper/Code/Navara/kennisfestival-iac --workspace-mount-consistency cached --id-label vsch.local.folder=/Users/casper/Code/Navara/kennisfestival-iac --id-label vsch.quality=stable --log-level debug --config /Users/casper/Code/Navara/kennisfestival-iac/.devcontainer/devcontainer.json --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[9468 ms] Exit code 1
```

**Comment by 792x** [comment]
Nog het een en het ander geprobeerd maar geen oplossing gevonden, neem vanmiddag een andere laptop mee.
